### PR TITLE
Creating German translation

### PR DESCRIPTION
**Pull request by aunwin**
including links to all and from all translations

### CODE REVIEW

**Comment by ncase** [comment]
Danke schön, @aunwin ! There hasn't been a new translation for this in almost 2 years –– glad to see it's still reaching & resonating with folks, and now thanks to you, it can reach even more folks :)

**Comment by aunwin** [comment]
Thanks for merging @ncase . I am glad that you consider it useful. I think you did great work here.
I came along your games while brainstorming how to create cool, some special and interactive explanations webpages.

**Comment by aunwin** [comment]
@ncase You may want to also add the entry of
[Deutsch](https://ncase.me/attractors/de.html) 
into the list of **Translations already done:** in your readme as soon as the german page is available.

Also I think it would be great to make the translations available more visible by putting links to them also on the top of the side, just as you did with https://ncase.me/polygons/

**Comment by ncase** [comment]
@aunwin Ahhhh sorry, I pulled to master, but I forgot that Github Pages was deploying from another branch. I added Deutsch to the Readme, and your Deutsch version is now _actually_ live at https://ncase.me/attractors/de.html 

Many thanks again! 🎉

**Pull request merged**
